training_data_paths:
- "./arrows/dataset.arrow"
probability:
- 1
context_length: 192
prediction_length: 12
min_past: 192
max_steps: 200_000
save_steps: 10_000
log_steps: 100
per_device_train_batch_size: 32
learning_rate: 0.0001
optim: adamw_torch_fused
num_samples: 20
shuffle_buffer_length: 10_000
gradient_accumulation_steps: 1
model_id: google/t5-efficient-small
model_type: seq2seq
random_init: true
tie_embeddings: true
output_dir: ./output/
tf32: true
torch_compile: true
tokenizer_class: "MeanScaleUniformBins"
tokenizer_kwargs:
  low_limit: -15.0
  high_limit: 15.0
n_tokens: 4096
lr_scheduler_type: linear
warmup_ratio: 0.0
dataloader_num_workers: 16
max_missing_prop: 0.9
use_eos_token: true